name: Bundle Stats

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: grafana/plugin-actions/bundle-size@979f3c7da9cf6f8f53d6d3c1e03b4298b4108c29 # main
