# This GitHub Action automates the process of building Grafana plugins.
# (For more information, see https://github.com/grafana/plugin-actions/blob/main/build-plugin/README.md)
name: Release

on:
  push:
    tags:
      - "v*" # Run workflow on version tags, e.g. v1.0.0.

permissions: read-all

jobs:
  release:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: grafana/plugin-actions/build-plugin@979f3c7da9cf6f8f53d6d3c1e03b4298b4108c29 # main
        # Uncomment to enable plugin signing
        # (For more info on how to generate the access policy token see https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin#generate-an-access-policy-token)
        #with:
        # Make sure to save the token in your repository secrets
        #policy_token: $
        # Usage of GRAFANA_API_KEY is deprecated, prefer `policy_token` option above
        #grafana_token: $
